version: '3.1'

#TODO find out why it doesn't work when it runs with the minikube docker deamon. Run in a separate shell
services:

  postgresql:
    image: postgres:10.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hibernate
      POSTGRES_PASSWORD: hibernate
      POSTGRES_DB: hibernate_db
