FROM postgres:10.5

RUN sh -c 'touch /etc/postgresql/postgresql.conf'

COPY etc/postgresql/postgresql.conf /etc/postgresql/postgresql.conf

ENV POSTGRES_USER=hibernate
ENV POSTGRES_PASSWORD=hibernate
ENV POSTGRES_DB=hibernate_db

EXPOSE 5432

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]